baseurl = "https://ricardolonga.github.io/"
languageCode = "en-us"
title = "Ricardo Longa"
theme = "hugo-cactus-theme"
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Ricardo Longa"
	bio = ""
	twitter = "ricardolonga"
	enableRSS = true

	customCSS = []
	customJS  = []

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	
	# Sharing options and author information in posts
	aboutAuthor = "I'm an Android and Backend developer..."
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
	
	# The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    	socialIconStyle = ""

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/ricardolonga"
    github   = "https://www.github.com/ricardolonga"
